[features]
seeds = false
skip-lint = false
[programs.localnet]
devnet_token_faucet = "DLr1ELqXdqAqf1TCuXedFx8YaVq4KQDudnAvprJcJjRt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/jamesl/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
